version: "3.8"
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgress/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres-db
  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - ./db-data/redis/:/data
      - ./db-data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASS: password

volumes:
  data: {}

networks:
  default:
    name: network